export const lordicons: Record<string, string> = {
    addCard: "https://cdn.lordicon.com/hqymfzvj.json",
    arroba: "https://cdn.lordicon.com/nzixoeyk.json",
    bin: "https://cdn.lordicon.com/skkahier.json",
    chat: "https://cdn.lordicon.com/fdxqrdfe.json",
    check: "https://cdn.lordicon.com/oqdmuxru.json",
    cross: "https://cdn.lordicon.com/nqtddedc.json",
    events: "https://cdn.lordicon.com/abfverha.json",
    exit: "https://cdn.lordicon.com/gwvmctbb.json",
    help: "https://cdn.lordicon.com/axteoudt.json",
    inbox: "https://cdn.lordicon.com/xtnsvhie.json",
    plusCircle: "https://cdn.lordicon.com/sbnjyzil.json",
    refresh: "https://cdn.lordicon.com/rsbokaso.json",
    results: "https://cdn.lordicon.com/zrtfxghu.json",
    search: "https://cdn.lordicon.com/kkvxgpti.json",
    settings: "https://cdn.lordicon.com/lecprnjb.json",
    share: "https://cdn.lordicon.com/ercyvufy.json",
    user: "https://cdn.lordicon.com/kthelypq.json",
    home: 'https://cdn.lordicon.com/cnpvyndp.json'
};
